In [2]:
import numpy as np
from scipy import linalg

In [10]:
A = np.array([
    [4, -1, 1],
    [6, -2, 1],
    [8, -8, 1],
    [5, -9, 1],
    [2, -10, 1],
    [0, -7, 1],
    [2, -5, 1]
])
B = np.array([4.125, 10, 32, 26.5, 26, 12.25, 7.25])

In [13]:
c1, c2, c3 = np.linalg.lstsq(A, B)[0]

/var/folders/qw/5rcwl4d96zvcq7zxv7fzt3m80000gn/T/ipykernel_11586/844213474.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  c1, c2, c3 = np.linalg.lstsq(A, B)[0]


In [14]:
c1, c2, c3

(2.139810240287448, -2.872967662250169, -8.616359757466885)

In [15]:
np.sqrt(c1**2 + c2**2 +c3)

2.053380455567682

In [7]:
np.matmul(A.T, B.T)

array([  5, -10])

In [20]:
def GramSchmidt(A):
    M = A.shape[0]
    N = A.shape[1]
    assert(M >= N)
    Q = np.zeros((M, N))
    for k in range(0, N):
        Q[:, k] = A[:, k]
        for j in range(0, k):
            Q[:, k] -= np.dot(Q[:, j], A[:, k]) * Q[:, j]
        Q[:, k] /= linalg.norm(Q[:, k])
    return Q

In [24]:
A = np.zeros((4,4))
A[:,0] = [1, -1, 1, -1]
A[:,1] = [1,1,3,-1]
A[:,2] = [-3,7,1,3]
A[:,3] = [0,0,0,1]

In [25]:
A

array([[ 1.,  1., -3.,  0.],
       [-1.,  1.,  7.,  0.],
       [ 1.,  3.,  1.,  0.],
       [-1., -1.,  3.,  1.]])

In [27]:
Q = GramSchmidt(A)
print(Q)

[[ 0.5         0.          0.          0.28867513]
 [-0.5         0.70710678  0.70710678 -0.28867513]
 [ 0.5         0.70710678  0.70710678  0.28867513]
 [-0.5         0.          0.          0.8660254 ]]


In [31]:
1/np.sqrt(12)

0.2886751345948129